<?php
echo "<!DOCTYPE html>\n"; 
echo "<html lang=\"en\">\n"; 
echo "\n"; 
echo "<head>\n"; 
echo "\n"; 
echo "    <meta charset=\"utf-8\">\n"; 
echo "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"; 
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"; 
echo "    <meta name=\"description\" content=\"\">\n"; 
echo "    <meta name=\"author\" content=\"\">\n"; 
echo "\n"; 
echo "    <title>PRatian</title>\n"; 
echo "\n"; 
echo "    <!-- Bootstrap Core CSS -->\n"; 
echo "    <link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\n"; 
echo "\n"; 
echo "    <!-- Custom Fonts -->\n"; 
echo "    <link href=\"vendor/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "    <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>\n"; 
echo "    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>\n"; 
echo "    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>\n"; 
echo "\n"; 
echo "    <!-- Theme CSS -->\n"; 
echo "    <link href=\"css/agency.min.css\" rel=\"stylesheet\">\n"; 
echo "\n"; 
echo "    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n"; 
echo "    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n"; 
echo "    <!--[if lt IE 9]>\n"; 
echo "        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n"; 
echo "        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\n"; 
echo "    <![endif]-->\n"; 
echo "\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body id=\"page-top\" class=\"index\">\n"; 
echo "\n"; 
echo "    <!-- Navigation -->\n"; 
echo "    <nav id=\"mainNav\" class=\"navbar navbar-default navbar-custom navbar-fixed-top\">\n"; 
echo "        <div class=\"container\">\n"; 
echo "            <!-- Brand and toggle get grouped for better mobile display -->\n"; 
echo "            <div class=\"navbar-header page-scroll\">\n"; 
echo "                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\n"; 
echo "                    <span class=\"sr-only\">Toggle navigation</span> Menu <i class=\"fa fa-bars\"></i>\n"; 
echo "                </button>\n"; 
echo "                <a href=\"#page-top\"><img src=\"img/PRatian_logo.jpg\" width=\"150\" height=\"75\"></a>\n"; 
echo "            </div>\n"; 
echo "\n"; 
echo "            <!-- Collect the nav links, forms, and other content for toggling -->\n"; 
echo "            <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\n"; 
echo "                <ul class=\"nav navbar-nav navbar-right\">\n"; 
echo "                    <li class=\"hidden\">\n"; 
echo "                        <a href=\"#page-top\"></a>\n"; 
echo "                    </li>\n"; 
echo "                    <li>\n"; 
echo "                        <a class=\"page-scroll\" href=\"#about\">About Us</a>\n"; 
echo "                    </li>\n"; 
echo "                    <li>\n"; 
echo "                        <a class=\"page-scroll\" href=\"#projects\">Projects</a>\n"; 
echo "                    </li>\n"; 
echo "                    <li>\n"; 
echo "                        <a class=\"page-scroll\" href=\"#team\">Team</a>\n"; 
echo "                    </li>\n"; 
echo "                    <li>\n"; 
echo "                        <a class=\"page-scroll\" href=\"#contact\">Contact Us</a>\n"; 
echo "                    </li>\n"; 
echo "                </ul>\n"; 
echo "            </div>\n"; 
echo "            <!-- /.navbar-collapse -->\n"; 
echo "        </div>\n"; 
echo "        <!-- /.container-fluid -->\n"; 
echo "    </nav>\n"; 
echo "\n"; 
echo "    <!-- Header -->\n"; 
echo "    <header>\n"; 
echo "        <div class=\"container\">\n"; 
echo "            <div class=\"intro-text\">\n"; 
echo "                <div class=\"intro-lead-in\"></div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </header>\n"; 
echo "\n"; 
echo "    <!-- About Section -->\n"; 
echo "    <section id=\"about\" class=\"bg-light-gray\">\n"; 
echo "      <div class=\"container\">\n"; 
echo "        <div class=\"row\">\n"; 
echo "          <div class=\"col-lg-12 text-center\">\n"; 
echo "            <h2 class=\"section-heading\">About Us</h2>\n"; 
echo "            <p class=\"text-muted\">We are a group of scientists, engineers, and entrepreneurs, who believe in potential Caribbean's development potential through the innovation of space technologies. We call this initiative PRatian as we are the first young Caribbean professionals to reach Mars and beyond. Our mission is to promote a culture of research towards innovation and commercialization of STEM developments with a non-restricted focus on space sciences. We aim to develop scientific projects for the well-being of society, ameliorating economic growth by creating products with high commercial value and strengthening worldwide connections within the scientific community. Our ultimate goal is to obtain scientific exposure internationally and design technologies to be commercialized. We are determined for Puerto Rico to be the founding location and headquarters of space research in the Caribbean.\n"; 
echo " \n"; 
echo "            On this website, you will be able to keep up to date with our events such as past and most recent research proposals, conferences and competitions attended, recognitions and awards granted, seminars to local communities conducted, and so on.</p>\n"; 
echo "          </div>\n"; 
echo "        </div>\n"; 
echo "      </div>\n"; 
echo "    </section>\n"; 
echo "\n"; 
echo "    <!-- Projects Grid Section -->\n"; 
echo "    <section id=\"projects\">\n"; 
echo "        <div class=\"container\">\n"; 
echo "            <div class=\"row\">\n"; 
echo "                <div class=\"col-lg-12 text-center\">\n"; 
echo "                    <h2 class=\"section-heading\">Projects</h2>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "\n"; 
echo "\n"; 
echo "            <div class=\"row\">\n"; 
echo "\n"; 
echo "                <div class=\"col-md-4 col-sm-6 portfolio-item\">\n"; 
echo "                    <a>\n"; 
echo "                        <img src=\"img/projects/1.png\" class=\"img-responsive\" alt=\"\">\n"; 
echo "                    </a>\n"; 
echo "                    <div class=\"portfolio-caption\">\n"; 
echo "                        <div class=\"text-center\">\n"; 
echo "\n"; 
echo "                            <h4>Mars Analog Campaign in Torun, Poland</h4>\n"; 
echo "                            <h5 class=\"subheading\">Project #1 - Spring 2017</h5>\n"; 
echo "                            <p class=\"text-muted\">Study of Plant Growth Under the Effects of Perchlorate and its Radiolysis\n"; 
echo "                          Products on Martian Surface.</p>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "\n"; 
echo "                <div class=\"col-md-4 col-sm-6 portfolio-item\">\n"; 
echo "                    <a>\n"; 
echo "                        <img src=\"img/projects/2.png\" class=\"img-responsive\" alt=\"\">\n"; 
echo "                    </a>\n"; 
echo "                    <div class=\"portfolio-caption\">\n"; 
echo "                        <div class=\"text-center\">\n"; 
echo "                            <h4>Innovative Transportation Systems for Mars City (with Applications on\n"; 
echo "                          Earth )</h4>\n"; 
echo "                            <h5 class=\"subheading\">Project #2 - Starting October 2016</h5>\n"; 
echo "                            <p class=\"text-muted\">Innovation of transportation systems for a Mars Design Contest with Commercial\n"; 
echo "                          Applications here on Earth.</p>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "\n"; 
echo "                <div class=\"col-md-4 col-sm-6 portfolio-item\">\n"; 
echo "                    <a>\n"; 
echo "                        <img src=\"img/projects/3.png\" class=\"img-responsive\" alt=\"\">\n"; 
echo "                    </a>\n"; 
echo "                    <div class=\"portfolio-caption\">\n"; 
echo "                        <div class=\"text-center\">\n"; 
echo "                            <h4>Microgravity Research for a Commercial Spaceflight</h4>\n"; 
echo "                            <h5 class=\"subheading\">Project #3 - Opportunity in Fall 2016</h5>\n"; 
echo "                            <p class=\"text-muted\">Design an antibacterial system, from naturally occurring products) that\n"; 
echo "                          can be used in the absence of gravity not only for personal hygiene but\n"; 
echo "                          for equipment safety and as a cleaning agent.</p>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "            <div class=\"row\">\n"; 
echo "                <div class=\"col-md-4 col-sm-6 portfolio-item\">\n"; 
echo "                    <a>\n"; 
echo "                        <img src=\"img/projects/4.png\" class=\"img-responsive\" alt=\"\">\n"; 
echo "                    </a>\n"; 
echo "                    <div class=\"portfolio-caption\">\n"; 
echo "                        <div class=\"text-center\">\n"; 
echo "                            <h4>Remote Sensing Using CubeSat Platforms</h4>\n"; 
echo "                            <h5 class=\"subheading\">Project #4 - Fall 2016</h5>\n"; 
echo "                            <p class=\"text-muted\">Innovative machine learning methods for detecting floods/zika/dengue propagation\n"; 
echo "                          along with the identification and monitoring of natural resources.</p>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "\n"; 
echo "                <div class=\"col-md-4 col-sm-6 portfolio-item\">\n"; 
echo "                    <a>\n"; 
echo "                        <img src=\"img/projects/5.png\" class=\"img-responsive\" alt=\"\">\n"; 
echo "                    </a>\n"; 
echo "                    <div class=\"portfolio-caption\">\n"; 
echo "                        <div class=\"text-center\">\n"; 
echo "                            <h4>Space Policy</h4>\n"; 
echo "                            <h5 class=\"subheading\">Project #5 - Spring 2017</h5>\n"; 
echo "                            <p class=\"text-muted\">Creation of Puerto Rican space policies to identify ideal country resources\n"; 
echo "                          and geographical locations used for research and development of space technologies.\n"; 
echo "                          Such policies will help structure the space market in the Caribbean and\n"; 
echo "                          attract investors to Puerto Rico.</p>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </section>\n"; 
echo "\n"; 
echo "    <!-- Team Section -->\n"; 
echo "    <section id=\"team\" class=\"bg-light-gray\">\n"; 
echo "        <div class=\"container\">\n"; 
echo "            <div class=\"row\">\n"; 
echo "                <div class=\"col-lg-12 text-center\">\n"; 
echo "                    <h2 class=\"section-heading\">Our Amazing Team</h2>\n"; 
echo "                    <h3 class=\"section-subheading text-muted\">Meet the PRatians</h3>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "\n"; 
echo "\n"; 
echo "            <div class=\"row\">\n"; 
echo "                <div class=\"col-sm-4\">\n"; 
echo "                    <div class=\"team-member\">\n"; 
echo "                        <a href=\"#portfolioModal1\" class=\"portfolio-link\" data-toggle=\"modal\">\n"; 
echo "                            <img src=\"img/team/axel.jpg\" class=\"img-responsive img-circle\" alt=\"\">\n"; 
echo "                        </a>\n"; 
echo "                        <h4>Axel Garcia Burgos</h4>\n"; 
echo "                        <p class=\"text-muted\"></p>\n"; 
echo "                        <ul class=\"list-inline social-buttons\">\n"; 
echo "                            <li><a href=\"https://www.linkedin.com/in/axel-garcia-69677436\"><i class=\"fa fa-linkedin\"></i></a>\n"; 
echo "                            </li>\n"; 
echo "                        </ul>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "\n"; 
echo "                <div class=\"col-sm-4\">\n"; 
echo "                    <div class=\"team-member\">\n"; 
echo "                        <a href=\"#portfolioModal2\" class=\"portfolio-link\" data-toggle=\"modal\">\n"; 
echo "                            <img src=\"img/team/nathasha.jpg\" class=\"img-responsive img-circle\" alt=\"\">\n"; 
echo "                        </a>\n"; 
echo "\n"; 
echo "                        <h4>Nathasha Rodriguez </h4>\n"; 
echo "                        <p class=\"text-muted\"></p>\n"; 
echo "                        <ul class=\"list-inline social-buttons\">\n"; 
echo "                            <li><a href=\"https://www.linkedin.com/in/nathasharodriguez\"><i class=\"fa fa-linkedin\"></i></a>\n"; 
echo "                            </li>\n"; 
echo "                        </ul>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "\n"; 
echo "                <div class=\"col-sm-4\">\n"; 
echo "                    <div class=\"team-member\">\n"; 
echo "                        <a href=\"#portfolioModal3\" class=\"portfolio-link\" data-toggle=\"modal\">\n"; 
echo "                            <img src=\"img/team/marcel.jpg\" class=\"img-responsive img-circle\" alt=\"\">\n"; 
echo "                        </a>\n"; 
echo "                        <h4> Marcel García Burgos</h4>\n"; 
echo "                        <p class=\"text-muted\"></p>\n"; 
echo "                        <ul class=\"list-inline social-buttons\">\n"; 
echo "                            <li><a href=\"https://www.linkedin.com/in/marcel-garcia\"><i class=\"fa fa-linkedin\"></i></a>\n"; 
echo "                            </li>\n"; 
echo "                        </ul>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "\n"; 
echo "            <div class=\"row\">\n"; 
echo "            \n"; 
echo "                <div class=\"col-sm-4\">\n"; 
echo "                    <div class=\"team-member\">\n"; 
echo "                        <a href=\"#portfolioModal4\" class=\"portfolio-link\" data-toggle=\"modal\">\n"; 
echo "                            <img src=\"img/team/keysha.jpg\" class=\"img-responsive img-circle\" alt=\"\">\n"; 
echo "                        </a>\n"; 
echo "                        <h4>Keysha M. González-Colón</h4>\n"; 
echo "                        <p class=\"text-muted\"></p>\n"; 
echo "                        <ul class=\"list-inline social-buttons\">\n"; 
echo "                            <li><a href=\"https://www.linkedin.com/in/keygonzalez\"><i class=\"fa fa-linkedin\"></i></a>\n"; 
echo "                            </li>\n"; 
echo "                        </ul>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            \n"; 
echo "\n"; 
echo "                <div class=\"col-sm-4\">\n"; 
echo "                    <div class=\"team-member\">\n"; 
echo "                        <a href=\"#portfolioModal5\" class=\"portfolio-link\" data-toggle=\"modal\">\n"; 
echo "                            <img src=\"img/team/carlos.jpg\" class=\"img-responsive img-circle\" alt=\"\">\n"; 
echo "                        </a>\n"; 
echo "                        <h4>Carlos A. Estévez-Galarza</h4>\n"; 
echo "                        <p class=\"text-muted\"></p>\n"; 
echo "                        <ul class=\"list-inline social-buttons\">\n"; 
echo "                            <li><a href=\"https://www.linkedin.com/in/carlos-est%C3%A9vez-galarza-a1a804126\"><i class=\"fa fa-linkedin\"></i></a>\n"; 
echo "                            </li>\n"; 
echo "                        </ul>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "\n"; 
echo "                <div class=\"col-sm-4\">\n"; 
echo "                    <div class=\"team-member\">\n"; 
echo "                        <a href=\"#portfolioModal6\" class=\"portfolio-link\" data-toggle=\"modal\">\n"; 
echo "                            <img src=\"img/team/abdiel.jpg\" class=\"img-responsive img-circle\" alt=\"\">\n"; 
echo "                        </a>\n"; 
echo "                        <h4> Abdiel A. Santos Galindo</h4>\n"; 
echo "                        <p class=\"text-muted\"></p>\n"; 
echo "                        <ul class=\"list-inline social-buttons\">\n"; 
echo "                            <li><a href=\"https://www.linkedin.com/in/abdielsantosg\"><i class=\"fa fa-linkedin\"></i></a>\n"; 
echo "                            </li>\n"; 
echo "                        </ul>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "\n"; 
echo "\n"; 
echo "            <div class=\"row\">\n"; 
echo "            \n"; 
echo "                <div class=\"col-sm-4\">\n"; 
echo "                    <div class=\"team-member\">\n"; 
echo "                        <a href=\"#portfolioModal7\" class=\"portfolio-link\" data-toggle=\"modal\">\n"; 
echo "                            <img src=\"img/team/gilberto.jpg\" class=\"img-responsive img-circle\" alt=\"\">\n"; 
echo "                        </a>\n"; 
echo "                        <h4>Gilberto Jimenez Orench</h4>\n"; 
echo "                        <p class=\"text-muted\"></p>\n"; 
echo "                        <ul class=\"list-inline social-buttons\">\n"; 
echo "                            <li><a href=\"http://linkedin.com/in/gilberto-jimenez-orench\"><i class=\"fa fa-linkedin\"></i></a>\n"; 
echo "                            </li>\n"; 
echo "                        </ul>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            \n"; 
echo "\n"; 
echo "                <div class=\"col-sm-4\">\n"; 
echo "                    <div class=\"team-member\">\n"; 
echo "                        <a href=\"#portfolioModal8\" class=\"portfolio-link\" data-toggle=\"modal\">\n"; 
echo "                            <img src=\"img/team/benedict.jpg\" class=\"img-responsive img-circle\" alt=\"\">\n"; 
echo "                        </a>\n"; 
echo "                        <h4>Benedict Pineyro </h4>\n"; 
echo "                        <p class=\"text-muted\"></p>\n"; 
echo "                        <ul class=\"list-inline social-buttons\">\n"; 
echo "                            <li><a href=\"https://www.linkedin.com/in/benedict-pineyro-21859649\"><i class=\"fa fa-linkedin\"></i></a>\n"; 
echo "                            </li>\n"; 
echo "                        </ul>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "\n"; 
echo "                <div class=\"col-sm-4\">\n"; 
echo "                    <div class=\"team-member\">\n"; 
echo "                        <a href=\"#portfolioModal9\" class=\"portfolio-link\" data-toggle=\"modal\">\n"; 
echo "                            <img src=\"img/team/sebastiani.jpg\" class=\"img-responsive img-circle\" alt=\"\">\n"; 
echo "                        </a>\n"; 
echo "                        <h4>Sebastiani Aguirre Navarro</h4>\n"; 
echo "                        <p class=\"text-muted\"></p>\n"; 
echo "                        <ul class=\"list-inline social-buttons\">\n"; 
echo "                            <li><a href=\"https://www.linkedin.com/in/sebastiani-aguirre-7aa02982/en\"><i class=\"fa fa-linkedin\"></i></a>\n"; 
echo "                            </li>\n"; 
echo "                        </ul>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "\n"; 
echo "\n"; 
echo "            <div class=\"row\">\n"; 
echo "            \n"; 
echo "                <div class=\"col-sm-4\">\n"; 
echo "                    <div class=\"team-member\">\n"; 
echo "                        <a href=\"#portfolioModal10\" class=\"portfolio-link\" data-toggle=\"modal\">\n"; 
echo "                            <img src=\"img/team/tatiana.jpg\" class=\"img-responsive img-circle\" alt=\"\">\n"; 
echo "                        </a>\n"; 
echo "                        <h4>Tatiana Vélez-Burgos</h4>\n"; 
echo "                        <p class=\"text-muted\"></p>\n"; 
echo "                        <ul class=\"list-inline social-buttons\">\n"; 
echo "                            <li><a href=\"https://pr.linkedin.com/in/tatianavb\"><i class=\"fa fa-linkedin\"></i></a>\n"; 
echo "                            </li>\n"; 
echo "                        </ul>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            \n"; 
echo "\n"; 
echo "                <div class=\"col-sm-4\">\n"; 
echo "                    <div class=\"team-member\">\n"; 
echo "                        <a href=\"#portfolioModal11\" class=\"portfolio-link\" data-toggle=\"modal\">\n"; 
echo "                            <img src=\"img/team/adrian.jpg\" class=\"img-responsive img-circle\" alt=\"\">\n"; 
echo "                        </a>\n"; 
echo "                        <h4>Adrian A. Lopez Caraballo</h4>\n"; 
echo "                        <p class=\"text-muted\"></p>\n"; 
echo "                        <ul class=\"list-inline social-buttons\">\n"; 
echo "                            <li><a href=\"https://pr.linkedin.com/in/adrian-lopez-caraballo-010b7b35\"><i class=\"fa fa-linkedin\"></i></a>\n"; 
echo "                            </li>\n"; 
echo "                        </ul>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "\n"; 
echo "                <div class=\"col-sm-4\">\n"; 
echo "                    <div class=\"team-member\">\n"; 
echo "                        <a href=\"#portfolioModal12\" class=\"portfolio-link\" data-toggle=\"modal\">\n"; 
echo "                            <img src=\"img/team/steven.jpg\" class=\"img-responsive img-circle\" alt=\"\">\n"; 
echo "                        </a>\n"; 
echo "                        <h4> Steven M. O'Neill Santiago</h4>\n"; 
echo "                        <p class=\"text-muted\"></p>\n"; 
echo "                        <ul class=\"list-inline social-buttons\">\n"; 
echo "                            <li><a href=\"https://www.linkedin.com/in/steven-o-neill-santiago-48270982\"><i class=\"fa fa-linkedin\"></i></a>\n"; 
echo "                            </li>\n"; 
echo "                        </ul>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "            <div class=\"row\">\n"; 
echo "            \n"; 
echo "                <div class=\"col-sm-4\">\n"; 
echo "                    <div class=\"team-member\">\n"; 
echo "                        <a href=\"#portfolioModal13\" class=\"portfolio-link\" data-toggle=\"modal\">\n"; 
echo "                            <img src=\"img/team/yoliem.jpg\" class=\"img-responsive img-circle\" alt=\"\">\n"; 
echo "                        </a>\n"; 
echo "                        <h4>Yoliem S. Miranda Alarcon</h4>\n"; 
echo "                        <p class=\"text-muted\"></p>\n"; 
echo "                        <ul class=\"list-inline social-buttons\">\n"; 
echo "                            <li><a href=\"https://www.linkedin.com/in/yoliem-s-miranda-alarcon-51790b123\"><i class=\"fa fa-linkedin\"></i></a>\n"; 
echo "                            </li>\n"; 
echo "                        </ul>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            \n"; 
echo "\n"; 
echo "                <div class=\"col-sm-4\">\n"; 
echo "                    <div class=\"team-member\">\n"; 
echo "                        <a href=\"#portfolioModal14\" class=\"portfolio-link\" data-toggle=\"modal\">\n"; 
echo "                            <img src=\"img/team/kevin.jpg\" class=\"img-responsive img-circle\" alt=\"\">\n"; 
echo "                        </a>\n"; 
echo "                        <h4>Kevin Torres Hernández</h4>\n"; 
echo "                        <p class=\"text-muted\"></p>\n"; 
echo "                        <ul class=\"list-inline social-buttons\">\n"; 
echo "                            <li><a href=\"https://pr.linkedin.com/in/kevin-torres-1ab32b77\"><i class=\"fa fa-linkedin\"></i></a>\n"; 
echo "                            </li>\n"; 
echo "                        </ul>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"col-sm-4\">\n"; 
echo "                    <div class=\"team-member\">\n"; 
echo "                        <a href=\"#portfolioModal15\" class=\"portfolio-link\" data-toggle=\"modal\">\n"; 
echo "                            <img src=\"img/team/johana.jpg\" class=\"img-responsive img-circle\" alt=\"\">\n"; 
echo "                        </a>\n"; 
echo "                        <h4> Johana M. Mercado Colón</h4>\n"; 
echo "                        <p class=\"text-muted\"></p>\n"; 
echo "                        <ul class=\"list-inline social-buttons\">\n"; 
echo "                            <li><a href=\"https://pr.linkedin.com/in/johana-mercado-col%C3%B3n-528080107\"><i class=\"fa fa-linkedin\"></i></a>\n"; 
echo "                            </li>\n"; 
echo "                        </ul>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "            <div class=\"col-sm-4\">\n"; 
echo "                <div class=\"team-member\">\n"; 
echo "                    <a href=\"#portfolioModal16\" class=\"portfolio-link\" data-toggle=\"modal\">\n"; 
echo "                        <img src=\"img/team/jose.jpg\" class=\"img-responsive img-circle\" alt=\"\" >\n"; 
echo "                    </a>\n"; 
echo "                    <h4>José Couvertier Garay</h4>\n"; 
echo "                    <p class=\"text-muted\"></p>\n"; 
echo "                    <ul class=\"list-inline social-buttons\">\n"; 
echo "                        <li><a href=\"https://www.linkedin.com/in/jose-couvertier-garay-40a0a382\"><i class=\"fa fa-linkedin\"></i></a>\n"; 
echo "                        </li>\n"; 
echo "                    </ul>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </section>\n"; 
echo "\n"; 
echo "    <!-- Contact Section -->\n"; 
echo "    <section id=\"contact\">\n"; 
echo "        <div class=\"container\">\n"; 
echo "            <div class=\"row\">\n"; 
echo "                <div class=\"col-lg-12 text-center\">\n"; 
echo "                    <h2 class=\"section-heading\">Contact Us</h2>\n"; 
echo "                    <h3 class=\"section-subheading text-muted\">Any questions?</h3>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "            <div class=\"row\">\n"; 
echo "                <div class=\"col-lg-12\">\n"; 
echo "                    <form name=\"sentMessage\" id=\"contactForm\" novalidate>\n"; 
echo "                        <div class=\"row\">\n"; 
echo "                            <div class=\"col-md-6\">\n"; 
echo "                                <div class=\"form-group\">\n"; 
echo "                                    <input type=\"text\" class=\"form-control\" placeholder=\"Your Name *\" id=\"name\" required data-validation-required-message=\"Please enter your name.\">\n"; 
echo "                                    <p class=\"help-block text-danger\"></p>\n"; 
echo "                                </div>\n"; 
echo "                                <div class=\"form-group\">\n"; 
echo "                                    <input type=\"email\" class=\"form-control\" placeholder=\"Your Email *\" id=\"email\" required data-validation-required-message=\"Please enter your email address.\">\n"; 
echo "                                    <p class=\"help-block text-danger\"></p>\n"; 
echo "                                </div>\n"; 
echo "                                <div class=\"form-group\">\n"; 
echo "                                    <input type=\"tel\" class=\"form-control\" placeholder=\"Your Phone *\" id=\"phone\" required data-validation-required-message=\"Please enter your phone number.\">\n"; 
echo "                                    <p class=\"help-block text-danger\"></p>\n"; 
echo "                                </div>\n"; 
echo "                            </div>\n"; 
echo "                            <div class=\"col-md-6\">\n"; 
echo "                                <div class=\"form-group\">\n"; 
echo "                                    <textarea class=\"form-control\" placeholder=\"Your Message *\" id=\"message\" required data-validation-required-message=\"Please enter a message.\"></textarea>\n"; 
echo "                                    <p class=\"help-block text-danger\"></p>\n"; 
echo "                                </div>\n"; 
echo "                            </div>\n"; 
echo "                            <div class=\"clearfix\"></div>\n"; 
echo "                            <div class=\"col-lg-12 text-center\">\n"; 
echo "                                <div id=\"success\"></div>\n"; 
echo "                                <button type=\"submit\" class=\"btn btn-xl\">Send Message</button>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </form>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </section>\n"; 
echo "\n"; 
echo "    <footer>\n"; 
echo "        <div class=\"container\">\n"; 
echo "            <div class=\"row\">\n"; 
echo "                <div class=\"col-md-4\">\n"; 
echo "                    <span class=\"copyright\"></span>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"col-md-4\">\n"; 
echo "                    <ul class=\"list-inline social-buttons\">\n"; 
echo "                        <li><a href=\"https://www.facebook.com/PRatianLLC\"><i class=\"fa fa-facebook\"></i></a>\n"; 
echo "                        </li>\n"; 
echo "                        <li><a href=\"http://www.linkedin.com/company/pratian\"><i class=\"fa fa-linkedin\"></i></a>\n"; 
echo "                        </li>\n"; 
echo "                    </ul>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"col-md-4\">\n"; 
echo "                    <ul class=\"list-inline quicklinks\">\n"; 
echo "                        <li><a href=\"#\"></a>\n"; 
echo "                        </li>\n"; 
echo "                        <li><a href=\"#\"></a>\n"; 
echo "                        </li>\n"; 
echo "                    </ul>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </footer>\n"; 
echo "\n"; 
echo "    <!-- Portfolio Modals -->\n"; 
echo "    <!-- Use the modals below to showcase details about your portfolio projects! -->\n"; 
echo "\n"; 
echo "    <!-- Portfolio Modal 1 -->\n"; 
echo "    <div class=\"portfolio-modal modal fade\" id=\"portfolioModal1\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n"; 
echo "        <div class=\"modal-dialog\">\n"; 
echo "            <div class=\"modal-content\">\n"; 
echo "                <div class=\"close-modal\" data-dismiss=\"modal\">\n"; 
echo "                    <div class=\"lr\">\n"; 
echo "                        <div class=\"rl\">\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"container\">\n"; 
echo "                    <div class=\"row\">\n"; 
echo "                        <div class=\"col-lg-8 col-lg-offset-2\">\n"; 
echo "                            <div class=\"modal-body\">\n"; 
echo "                                <!-- Project Details Go Here -->\n"; 
echo "                                <h2>Axel Garcia Burgos</h2>\n"; 
echo "                                <p class=\"item-intro text-muted\">President</p>\n"; 
echo "                                <img class=\"img-responsive img-centered\" src=\"img/team/Axel.png\" alt=\"\">\n"; 
echo "                                <p align=\"justify\">Garcia joined NASA GSFC as a civil servant in 2015 after having interned at NASA Kennedy Space Center, NASA Ames Research Center, and NASA Goddard since 2010. Besides working at NASA Goddard, Axel is pursuing his graduate studies in Space Science and Technology from a joint program between MIT and the Skolkovo Institute of Science and Technology in Moscow, Russia.  Garcia’s experience focuses on spacecraft development and space innovation.  He is working towards a NASA systems engineer position, leading the future projects of deep space missions. He’s also a scientist- astronaut candidate for the upcoming commercial spaceflight opportunities starting in 2020.</p>\n"; 
echo "                                <p align=\"justify\">Garcia would like to contribute to the development of Puerto Rican society and human space exploration. Garcia firmly believes that the commercialization of space technologies can ameliorate and create a new market that could help increase our economy. Pratian LLC aims for the development of such technologies.</p>\n"; 
echo "                                <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\"><i class=\"fa fa-times\"></i>Close</button>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "    <!-- Portfolio Modal 2 -->\n"; 
echo "    <div class=\"portfolio-modal modal fade\" id=\"portfolioModal2\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n"; 
echo "        <div class=\"modal-dialog\">\n"; 
echo "            <div class=\"modal-content\">\n"; 
echo "                <div class=\"close-modal\" data-dismiss=\"modal\">\n"; 
echo "                    <div class=\"lr\">\n"; 
echo "                        <div class=\"rl\">\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"container\">\n"; 
echo "                    <div class=\"row\">\n"; 
echo "                        <div class=\"col-lg-8 col-lg-offset-2\">\n"; 
echo "                            <div class=\"modal-body\">\n"; 
echo "                                <!-- Project Details Go Here -->\n"; 
echo "                                <h2>Nathasha Rodriguez</h2>\n"; 
echo "                                <p class=\"item-intro text-muted\">Vice President of Strategy</p>\n"; 
echo "                                <img class=\"img-responsive img-centered\" src=\"img/team/nathasha.png\" alt=\"\">\n"; 
echo "                                <p align=\"justify\">Rodriguez graduated from the Massachusetts Institute of Technology (MIT) with a major in Management Science, an interdisciplinary major that combines business, math, and analytics coursework, with concentrations in Finance and Portuguese. Nathasha’s professional background is in technology commercialization – she has been fortunate to utilize her business, research, and data analysis skills to advance technological and scientific innovations that will make the world a better place. All her life Nathasha has considered space to be fascinating, and she joined Pratian LLC to contribute to the space-research community while achieving her goal of giving back to her homeland, Puerto Rico.</p>\n"; 
echo "\n"; 
echo "                                <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\"><i class=\"fa fa-times\"></i> Close</button>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "    <!-- Portfolio Modal 3 -->\n"; 
echo "    <div class=\"portfolio-modal modal fade\" id=\"portfolioModal3\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n"; 
echo "        <div class=\"modal-dialog\">\n"; 
echo "            <div class=\"modal-content\">\n"; 
echo "                <div class=\"close-modal\" data-dismiss=\"modal\">\n"; 
echo "                    <div class=\"lr\">\n"; 
echo "                        <div class=\"rl\">\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"container\">\n"; 
echo "                    <div class=\"row\">\n"; 
echo "                        <div class=\"col-lg-8 col-lg-offset-2\">\n"; 
echo "                            <div class=\"modal-body\">\n"; 
echo "                                <!-- Team Details Here -->\n"; 
echo "                                <h2>Marcel Garcia Burgos</h2>\n"; 
echo "                                <p class=\"item-intro text-muted\">Buisness Director</p>\n"; 
echo "                                <img class=\"img-responsive img-centered\" src=\"img/team/marcel.png\" alt=\"\">\n"; 
echo "                                <p align=\"justify\">Marcel Garcia, a Summa Cum Laude graduate from Syracuse University, is an entrepreneur and soon to be lawyer. He has completed studies and worked in more than 4 continents over the last 8 years of his academic and professional career. His extensive list of experiences both nationally and internationally makes him a valuable and indispensable asset under the Business Division within our team. Marcel García believes that it is only with a strong joint venture among young professionals from different backgrounds and skills that PRatian LLC will be able to provide to our current and future generation a promising future through the development of space technologies and research in the caribe.</p>\n"; 
echo "\n"; 
echo "                                <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\"><i class=\"fa fa-times\"></i> Close</button>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "\n"; 
echo "    <!-- Portfolio Modal 4 -->\n"; 
echo "    <div class=\"portfolio-modal modal fade\" id=\"portfolioModal4\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n"; 
echo "        <div class=\"modal-dialog\">\n"; 
echo "            <div class=\"modal-content\">\n"; 
echo "                <div class=\"close-modal\" data-dismiss=\"modal\">\n"; 
echo "                    <div class=\"lr\">\n"; 
echo "                        <div class=\"rl\">\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"container\">\n"; 
echo "                    <div class=\"row\">\n"; 
echo "                        <div class=\"col-lg-8 col-lg-offset-2\">\n"; 
echo "                            <div class=\"modal-body\">\n"; 
echo "                                <!-- Team Details Here -->\n"; 
echo "                                <h2>Keysha M. González-Colón</h2>\n"; 
echo "                                <p class=\"item-intro text-muted\">Vice President of IT/CyberSecurity</p>\n"; 
echo "                                <img class=\"img-responsive img-centered\" src=\"img/team/keysha.png\" alt=\"\">\n"; 
echo "                                <p align=\"justify\">During her undergraduate years, González participated in various research programs in the UPRM to establish communication protocols to transfer audio data through a computational framework for the analysis and understanding of data collected for environmental surveillance monitoring, as well as the creation of a communication network to use a hardware and software platform for M2M applications. Her previous professional experiences include internship as Software Engineer and Systems Engineer for technology companies such as Harris Corp and Verizon. She joined Johnson and Johnson as part of the Information Technology Leadership Development Program.</p>\n"; 
echo "                                <p align=\"justify\">González is passionate about technology and science. As many other young professionals, she wants to contribute to the development of Puerto Rico’s technology capabilities. She believes Puerto Rico possess enough talent to innovate and help emerge the economy of the island cultivating education in technology and science as the main focus. With her work, she expects to be an example for our next generations to keep working to make Puerto Rico one of the top technology countries worldwide.</p>\n"; 
echo "                                <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\"><i class=\"fa fa-times\"></i> Close</button>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "\n"; 
echo "    <!-- Portfolio Modal 5 -->\n"; 
echo "    <div class=\"portfolio-modal modal fade\" id=\"portfolioModal5\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n"; 
echo "        <div class=\"modal-dialog\">\n"; 
echo "            <div class=\"modal-content\">\n"; 
echo "                <div class=\"close-modal\" data-dismiss=\"modal\">\n"; 
echo "                    <div class=\"lr\">\n"; 
echo "                        <div class=\"rl\">\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"container\">\n"; 
echo "                    <div class=\"row\">\n"; 
echo "                        <div class=\"col-lg-8 col-lg-offset-2\">\n"; 
echo "                            <div class=\"modal-body\">\n"; 
echo "                                <!-- Team Details Here -->\n"; 
echo "                                <h2>Carlos A. Estévez-Galarza</h2>\n"; 
echo "                                <p class=\"item-intro text-muted\">Space Research Director</p>\n"; 
echo "                                <img class=\"img-responsive img-centered\" src=\"img/team/carlos.png\" alt=\"\">\n"; 
echo "                                <p align=\"justify\">Estévez has worked at the Arecibo Observatory as a planetary science researcher. Currently, he analyzes data from MSL’s Curiosity rover, specifically from its REMS station. The MSL’s REMS was  recently used to suggest the possibility of liquid water formation via deliquescence of perchlorate salts during the Martian night (Martín-Torres et al., 2015). During his time in Arecibo, he has learned that planetary science is all about understanding  our world better by comparing it with other worlds. I think most of the people ignore science because its apparent difficulty scares them off, but somehow planetary science gets to people. It’s something people can visualize and feel identified with. I truly believe that  planetary science can give everyone the same feeling I perceived while doing my research. Through PRatian, I can bring this message  to more human beings, especially to underrepresented communities in science such as  Puerto Rico. Estévez believes on building a space sciences research center to be devoted to the  advancement of science and education in Puerto Rico, as well as a tool to grow our economy.</p>\n"; 
echo "                                <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\"><i class=\"fa fa-times\"></i> Close</button>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "    <!-- Portfolio Modal 6 -->\n"; 
echo "    <div class=\"portfolio-modal modal fade\" id=\"portfolioModal6\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n"; 
echo "        <div class=\"modal-dialog\">\n"; 
echo "            <div class=\"modal-content\">\n"; 
echo "                <div class=\"close-modal\" data-dismiss=\"modal\">\n"; 
echo "                    <div class=\"lr\">\n"; 
echo "                        <div class=\"rl\">\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"container\">\n"; 
echo "                    <div class=\"row\">\n"; 
echo "                        <div class=\"col-lg-8 col-lg-offset-2\">\n"; 
echo "                            <div class=\"modal-body\">\n"; 
echo "                                <!-- Team Details Here -->\n"; 
echo "                                <h2>Abdiel A. Santos Galindo</h2>\n"; 
echo "                                <p class=\"item-intro text-muted\">Vice President of Commericial Research</p>\n"; 
echo "                                <img class=\"img-responsive img-centered\" src=\"img/team/abdiel.png\" alt=\"\">\n"; 
echo "                                <p align=\"justify\">Santos had the opportunity of being a part of NASA’s Kennedy Space Center (KSC) family during an internship in 2011. His work included, but was not limited to, the integration of Unmanned Aircraft Vehicles (UAV’s) at KSC and his current university as well as the development of a robotics project for the island of Puerto Rico and a shadow opportunity for the STS-135 Space Shuttle mission. To this date he has worked on several CubeSat’s ranging from a satellite for the Air Force Space Research Lab to creating a team at the university to develop a rapid design CubeSat schedule to launch in the near future. He also presented his research on higher earth orbit for CubeSats and interplanetary mission concepts at the ISS RnD and HENAAC conferences. As he continues to pursue his degree he has also worked with other projects that relate to astronautics and hopes to land an opportunity with the launch operations team at KSC being at the controls of the rockets and missions that will expand humanity's knowledge and future in space.</p>\n"; 
echo "                                <p align=\"justify\">Even though Santos currently lives in Florida, he is committed give back to his island. Puerto Rico has a lot of potential to expand its horizons in the space program and STEM fields research and development. He believes that with the right team, enthusiasm, knowledge and ideas; new frontiers can be explored with the island and PRatians is the cornerstone to this new era.</p>\n"; 
echo "                                <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\"><i class=\"fa fa-times\"></i> Close</button>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "\n"; 
echo "    <!-- Portfolio Modal 7 -->\n"; 
echo "    <div class=\"portfolio-modal modal fade\" id=\"portfolioModal7\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n"; 
echo "        <div class=\"modal-dialog\">\n"; 
echo "            <div class=\"modal-content\">\n"; 
echo "                <div class=\"close-modal\" data-dismiss=\"modal\">\n"; 
echo "                    <div class=\"lr\">\n"; 
echo "                        <div class=\"rl\">\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"container\">\n"; 
echo "                    <div class=\"row\">\n"; 
echo "                        <div class=\"col-lg-8 col-lg-offset-2\">\n"; 
echo "                            <div class=\"modal-body\">\n"; 
echo "                                <!-- Team Details Here -->\n"; 
echo "                                <h2>Abdiel A. Santos Galindo</h2>\n"; 
echo "                                <p class=\"item-intro text-muted\">Vice President of Commerical Research</p>\n"; 
echo "                                <img class=\"img-responsive img-centered\" src=\"img/team/gilberto.png\" alt=\"\">\n"; 
echo "                                <p align=\"justify\">Jimenez works mostly as a Software Engineer with high level languages and cybersecurity. His past work experiences is wide and includes federal agencies and contractors which makes him knowledgeable on international relations subjects. Within PRatian LLC, he contributes to the organization, development and fulfillment of projects both from technical and non-technical perspectives.</p>\n"; 
echo "                                <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\"><i class=\"fa fa-times\"></i> Close</button>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "    <!-- Portfolio Modal 8 -->\n"; 
echo "    <div class=\"portfolio-modal modal fade\" id=\"portfolioModal8\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n"; 
echo "        <div class=\"modal-dialog\">\n"; 
echo "            <div class=\"modal-content\">\n"; 
echo "                <div class=\"close-modal\" data-dismiss=\"modal\">\n"; 
echo "                    <div class=\"lr\">\n"; 
echo "                        <div class=\"rl\">\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"container\">\n"; 
echo "                    <div class=\"row\">\n"; 
echo "                        <div class=\"col-lg-8 col-lg-offset-2\">\n"; 
echo "                            <div class=\"modal-body\">\n"; 
echo "                                <!-- Team Details Here -->\n"; 
echo "                                <h2>Benedict Pineyro</h2>\n"; 
echo "                                <p class=\"item-intro text-muted\">Vice President of Research and Development</p>\n"; 
echo "                                <img class=\"img-responsive img-centered\" src=\"img/team/benedict.png\" alt=\"\">\n"; 
echo "                                <p align=\"justify\">Pineyro has sought to gain exposure in several fields in order to expand his horizons. Benedict's background has allowed him to adapt to topics ranging from identifying submerged aquatic vegetation using remote sensing data of the Indian River Lagoon to text analytics of customer complaints at The Hartford. He will be interested in tackling new challenges brought by the PRatian Initiative. In addition, he'd like to be a part of the movement that makes the Caribbean a metonym for innovation.</p>\n"; 
echo "                                <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\"><i class=\"fa fa-times\"></i> Close</button>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "\n"; 
echo "    <!-- Portfolio Modal 9 -->\n"; 
echo "    <div class=\"portfolio-modal modal fade\" id=\"portfolioModal9\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n"; 
echo "        <div class=\"modal-dialog\">\n"; 
echo "            <div class=\"modal-content\">\n"; 
echo "                <div class=\"close-modal\" data-dismiss=\"modal\">\n"; 
echo "                    <div class=\"lr\">\n"; 
echo "                        <div class=\"rl\">\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"container\">\n"; 
echo "                    <div class=\"row\">\n"; 
echo "                        <div class=\"col-lg-8 col-lg-offset-2\">\n"; 
echo "                            <div class=\"modal-body\">\n"; 
echo "                                <!-- Team Details Here -->\n"; 
echo "                                <h2>Sebastiani Aguirre Navarro</h2>\n"; 
echo "                                <p class=\"item-intro text-muted\">Vice President of Research and Development</p>\n"; 
echo "                                <img class=\"img-responsive img-centered\" src=\"img/team/sebastiani.png\" alt=\"\">\n"; 
echo "                                <p align=\"justify\">Aguirre has conducted research in natural language processing and machine learning, thermal biophysics of cancer tumors and modeling, control and hardware design of autonomous vehicles. He would like to contribute to the development of Puerto Rico and he believes PRatian LLC is a good way to start applying his skills.</p>\n"; 
echo "                                <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\"><i class=\"fa fa-times\"></i> Close</button>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "\n"; 
echo "    <!-- Portfolio Modal 10 -->\n"; 
echo "    <div class=\"portfolio-modal modal fade\" id=\"portfolioModal10\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n"; 
echo "        <div class=\"modal-dialog\">\n"; 
echo "            <div class=\"modal-content\">\n"; 
echo "                <div class=\"close-modal\" data-dismiss=\"modal\">\n"; 
echo "                    <div class=\"lr\">\n"; 
echo "                        <div class=\"rl\">\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"container\">\n"; 
echo "                    <div class=\"row\">\n"; 
echo "                        <div class=\"col-lg-8 col-lg-offset-2\">\n"; 
echo "                            <div class=\"modal-body\">\n"; 
echo "                                <!-- Team Details Here -->\n"; 
echo "                                <h2>Tatiana Vélez-Burgos</h2>\n"; 
echo "                                <p class=\"item-intro text-muted\">Vice President of Human Factors</p>\n"; 
echo "                                <img class=\"img-responsive img-centered\" src=\"img/team/tatiana.png\" alt=\"\">\n"; 
echo "                                <p align=\"justify\">Vélez’s previous work experience includes development and optimization of analytical techniques such as Near Infrared Spectroscopy for Pharmaceutical and process analytical technologies (PAT). Furthermore, experience in the area of pharmaceutical processes for the implementation of PAT in the pharmaceutical industry. Moreover, current graduate school work include the development of Mass Spectrometry analytical methods for the identification of diseases (such as malaria and cancer).</p>\n"; 
echo "                                <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\"><i class=\"fa fa-times\"></i> Close</button>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "    <!-- Portfolio Modal 11 -->\n"; 
echo "    <div class=\"portfolio-modal modal fade\" id=\"portfolioModal11\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n"; 
echo "        <div class=\"modal-dialog\">\n"; 
echo "            <div class=\"modal-content\">\n"; 
echo "                <div class=\"close-modal\" data-dismiss=\"modal\">\n"; 
echo "                    <div class=\"lr\">\n"; 
echo "                        <div class=\"rl\">\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"container\">\n"; 
echo "                    <div class=\"row\">\n"; 
echo "                        <div class=\"col-lg-8 col-lg-offset-2\">\n"; 
echo "                            <div class=\"modal-body\">\n"; 
echo "                                <!-- Team Details Here -->\n"; 
echo "                                <h2>Adrian A. Lopez Caraballo</h2>\n"; 
echo "                                <p class=\"item-intro text-muted\">Vice President of Human Factors</p>\n"; 
echo "                                <img class=\"img-responsive img-centered\" src=\"img/team/adrian.png\" alt=\"\">\n"; 
echo "                                <p align=\"justify\">Lopez’s experience is focused on the Microbial Ecology area with microbes for extreme environments. By studying this microbes we can truly understand how life would be in other planets. Likewise, he has some experience in studying Microalgae ecology system for use on future Close Ecological Life Support System as well as in the Bioenergy area. He is currently working in the Biopharmaceutical Industry as a private contractor. His interest in PRatian LLC is to promote the space science area in Puerto Rico as well as Space Biology and Astrobiology. Through the PRatian initiative, he believes we would be able to successfully prepare a new generation of professionals on the Space Science area.</p>\n"; 
echo "                                <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\"><i class=\"fa fa-times\"></i> Close</button>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "    <!-- Portfolio Modal 12 -->\n"; 
echo "    <div class=\"portfolio-modal modal fade\" id=\"portfolioModal12\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n"; 
echo "        <div class=\"modal-dialog\">\n"; 
echo "            <div class=\"modal-content\">\n"; 
echo "                <div class=\"close-modal\" data-dismiss=\"modal\">\n"; 
echo "                    <div class=\"lr\">\n"; 
echo "                        <div class=\"rl\">\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"container\">\n"; 
echo "                    <div class=\"row\">\n"; 
echo "                        <div class=\"col-lg-8 col-lg-offset-2\">\n"; 
echo "                            <div class=\"modal-body\">\n"; 
echo "                                <!-- Team Details Here -->\n"; 
echo "                                <h2>Steven M. O'Neill Santiago</h2>\n"; 
echo "                                <p class=\"item-intro text-muted\">Vice President of Public Relations</p>\n"; 
echo "                                <img class=\"img-responsive img-centered\" src=\"img/team/steven.png\" alt=\"\">\n"; 
echo "                                <p align=\"justify\">O'Neill worked hands on with multiple commercial jet engines such as PW4000 (various model) and the CF34 (various model) at Delta TechOps (Delta airlines) Atlanta, GA. He was responsible for developing repairs to meet FAA requirement and performing them. Currently he works at QuEST-Global as a Tool Engineer for the F135 Jet Engine corresponding to the F35 Fighter jet. He is in charge of developing new tools and improving existing ones to perform repairs on the engine.</p>\n"; 
echo "                                <p align=\"justify\"> His input to PRatian LLC is how to convert an idea into profit and how to improve any process. He is particularly interested on how our research can become a solution to problems in space and in our planet.</p>\n"; 
echo "                                <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\"><i class=\"fa fa-times\"></i> Close</button>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "    <!-- Portfolio Modal 13 -->\n"; 
echo "    <div class=\"portfolio-modal modal fade\" id=\"portfolioModal13\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n"; 
echo "        <div class=\"modal-dialog\">\n"; 
echo "            <div class=\"modal-content\">\n"; 
echo "                <div class=\"close-modal\" data-dismiss=\"modal\">\n"; 
echo "                    <div class=\"lr\">\n"; 
echo "                        <div class=\"rl\">\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"container\">\n"; 
echo "                    <div class=\"row\">\n"; 
echo "                        <div class=\"col-lg-8 col-lg-offset-2\">\n"; 
echo "                            <div class=\"modal-body\">\n"; 
echo "                                <!-- Team Details Here -->\n"; 
echo "                                <h2>Yoliem S. Miranda Alarcon</h2>\n"; 
echo "                                <p class=\"item-intro text-muted\">Researcher</p>\n"; 
echo "                                <img class=\"img-responsive img-centered\" src=\"img/team/yoliem.png\" alt=\"\">\n"; 
echo "                                <p align=\"justify\">During her academic career with a particular interest in teaching science, she joined the American Chemistry Society (ACS). There, Miranda was part of the outreach group to carry out demonstrations of basic experiments to high school students in order to make science a more approachable field of study. As an undergrad, she worked in different research projects mainly in synthetic organic chemistry and tissue engineering.  This inspired her to continue graduate studies in the biomedical engineering field. Yoliem is currently pursuing her Masters of Science in biomedical engineering at Rutgers University- New Brunswick Campus, New Jersey. She is also working as a student researcher in the area of drug metabolism and pharmacokinetics at GlaxoSmithKline in Collegeville, PA. Other research areas Yoliem has been able to explore are in developmental biology at Memorial Sloan Kettering Cancer Center in New York, NY and Photochemistry/Biochemistry in SUNY-University at Albany, NY. For Miranda, is very important that prospect students are aware of all the opportunities in the STEM field. PRatian is a great platform for underrepresented students who are seeking guidance to pursue a career in the STEM field. As a community we can help bridge the gaps between the private sector and the academia.</p>\n"; 
echo "                                <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\"><i class=\"fa fa-times\"></i> Close</button>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "    <!-- Portfolio Modal 14 -->\n"; 
echo "    <div class=\"portfolio-modal modal fade\" id=\"portfolioModal14\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n"; 
echo "        <div class=\"modal-dialog\">\n"; 
echo "            <div class=\"modal-content\">\n"; 
echo "                <div class=\"close-modal\" data-dismiss=\"modal\">\n"; 
echo "                    <div class=\"lr\">\n"; 
echo "                        <div class=\"rl\">\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"container\">\n"; 
echo "                    <div class=\"row\">\n"; 
echo "                        <div class=\"col-lg-8 col-lg-offset-2\">\n"; 
echo "                            <div class=\"modal-body\">\n"; 
echo "                                <!-- Team Details Here -->\n"; 
echo "                                <h2> Kevin Torres Hernández</h2>\n"; 
echo "                                <p class=\"item-intro text-muted\">Researcher</p>\n"; 
echo "                                <img class=\"img-responsive img-centered\" src=\"img/team/kevin.png\" alt=\"\">\n"; 
echo "                                <p align=\"justify\">Torres’ exposure to STEM related opportunities started in 2008 when he was accepted into the NASA INSPIRE program.  He continued participating throughout his academic  career, first as a student and later as a mentor for new scholars.  In 2013, after the program  ended, he conducted research at the Electronic Department of the University of Puerto Rico in  Bayamón (UPRB) and transferred to University of Puerto Rico in Mayagüez (UPRM) to  continue his studies in Civil Engineering. He is currently a member of the Dynamic Aerospace  Rocketry Team (DART) of UPRM, which gives him the opportunity to be working in a  multidisciplinary environment.</p>\n"; 
echo "                                <p align=\"justify\">Torres’s interest in PRatian comes from the desire to learn and grow not just professionally but also  personally. This initiative gives him the opportunity to continue his dreams and ambitions from  the comfort of his home while also contributing to the development and growth of the country,  both economically and socially.  He understands that as we are researching and developing new ideas that could help us move beyond the limits of our horizon, we would also be inspiring future generations of Puerto Ricans to pursue an education in STEM fields. In his belief, it is  extremely important that we find new technologies that will better protect us and it is easily  integrated to the spaceships of tomorrow that, in turn, would allow us to travel safely to the Moon, Mars and beyond.</p>\n"; 
echo "                                <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\"><i class=\"fa fa-times\"></i> Close</button>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "    <!-- Portfolio Modal 15 -->\n"; 
echo "    <div class=\"portfolio-modal modal fade\" id=\"portfolioModal15\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n"; 
echo "        <div class=\"modal-dialog\">\n"; 
echo "            <div class=\"modal-content\">\n"; 
echo "                <div class=\"close-modal\" data-dismiss=\"modal\">\n"; 
echo "                    <div class=\"lr\">\n"; 
echo "                        <div class=\"rl\">\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"container\">\n"; 
echo "                    <div class=\"row\">\n"; 
echo "                        <div class=\"col-lg-8 col-lg-offset-2\">\n"; 
echo "                            <div class=\"modal-body\">\n"; 
echo "                                <!-- Team Details Here -->\n"; 
echo "                                <h2>Johana M. Mercado Colón</h2>\n"; 
echo "                                <p class=\"item-intro text-muted\">Researcher</p>\n"; 
echo "                                <img class=\"img-responsive img-centered\" src=\"img/team/johana.png\" alt=\"\">\n"; 
echo "                                <p align=\"justify\">Mercado, 2014-2015 Puerto Rico FFA State President, has conducted several research projects as a participant of the academies of Ana G. Mendez University System. In 2014 worked on a project in partnership with NASA Ames Research Center where worked on identifying and proposing necessary sensors and components to simulate the greenhouse effect for plant survival inside a Cube Sat on Mars. That same  year she did an extensive research in the field of electromagnetism and Laser Imaging Detection and Ranging technology and compared LIDAR technology with existing antennas and wave propagation system in the Arecibo Observatory. Mercado is also certified by Honeywell, Intelitek and Learning Labs Robotics in a Robotics and Automation Training. Currently, she collaborates in research projects at the Center for Biomedical Nanotechnology, Sustainability and Environmental Applications ​​at the UPRM (CREST) and belongs to the Society of Women Engineers (SWE) UPRM Chapter. Although among her future plans is to finish her bachelor's degree and pursue graduate studies in the field of bioengineering , she is committed to make a ​​positive impact in  agriculture and Space Science sector as a future engineer. </p>\n"; 
echo "                                <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\"><i class=\"fa fa-times\"></i> Close</button>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "    <!-- Portfolio Modal 16 -->\n"; 
echo "    <div class=\"portfolio-modal modal fade\" id=\"portfolioModal16\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n"; 
echo "        <div class=\"modal-dialog\">\n"; 
echo "            <div class=\"modal-content\">\n"; 
echo "                <div class=\"close-modal\" data-dismiss=\"modal\">\n"; 
echo "                    <div class=\"lr\">\n"; 
echo "                        <div class=\"rl\">\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "                <div class=\"container\">\n"; 
echo "                    <div class=\"row\">\n"; 
echo "                        <div class=\"col-lg-8 col-lg-offset-2\">\n"; 
echo "                            <div class=\"modal-body\">\n"; 
echo "                                <!-- Team Details Here -->\n"; 
echo "                                <h2>José Couvertier Garay</h2>\n"; 
echo "                                <p class=\"item-intro text-muted\">Business Consultant</p>\n"; 
echo "                                <img class=\"img-responsive img-centered\" src=\"img/team/jose.png\" alt=\"\">\n"; 
echo "                                <p align=\"justify\">While at Mayaguez, he participated in different scientific researches in and off campus in various topics of science including chemical, biological and engineering sciences. After obtaining his bachelor degree, due to his new found interests in businesses he went on to pursue a Juris Doctor at the University of Puerto Rico Law School in hopes of becoming an Intellectual Property Lawyer. Currently, he works as a law clerk in a Labor and Civil Law firm.  He has always been interested in companies and their contribution to society. He believes that not only he can grow as a professional by being part of PRatian, but also, can contribute with his knowledge in science, law, public relations and business to its growth while helping his country.</p>\n"; 
echo "                                <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\"><i class=\"fa fa-times\"></i> Close</button>\n"; 
echo "                            </div>\n"; 
echo "                        </div>\n"; 
echo "                    </div>\n"; 
echo "                </div>\n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "    <!-- jQuery -->\n"; 
echo "    <script src=\"vendor/jquery/jquery.min.js\"></script>\n"; 
echo "\n"; 
echo "    <!-- Bootstrap Core JavaScript -->\n"; 
echo "    <script src=\"vendor/bootstrap/js/bootstrap.min.js\"></script>\n"; 
echo "\n"; 
echo "    <!-- Plugin JavaScript -->\n"; 
echo "    <script src=\"http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js\"></script>\n"; 
echo "\n"; 
echo "    <!-- Contact Form JavaScript -->\n"; 
echo "    <script src=\"js/jqBootstrapValidation.js\"></script>\n"; 
echo "    <script src=\"js/contact_me.js\"></script>\n"; 
echo "\n"; 
echo "    <!-- Theme JavaScript -->\n"; 
echo "    <script src=\"js/agency.min.js\"></script>\n"; 
echo "\n"; 
echo "</body>\n"; 
echo "\n"; 
echo "</html>\n";
?>